config/routes.rb
Rails.application.routes.draw do
  resources :megusta
  resources :respuesta
  resources :comentarios
  resources :fotos
  resources :unirs
  get 'choise/index'

  resources :grupos
  get 'controlador/index'

  resources :cps
  resources :perfils
  devise_for :users, :controllers => { :omniauth_callbacks => "callbacks" }
  get 'home/index'

  resources :registros
  get 'join' => 'registros#join', as: :join
  get 'privado' => 'registros#private', as: :private
  get 'comenzar' => 'registros#comenzar', as: :comenzar
  get 'home' => 'home#index', as: :home
  get 'perfil' => 'perfils#new', as: :profile
  get 'webhook' => 'bot#webhook', as: :webhook
  get 'bot/webhook' => 'bot#webhook'
  post 'bot/webhook' => 'bot#receive_message'
  get 'unjoin' => 'registros#eliminar' , as: :unjoin
  get 'delete_images' => 'registros#eliminar_imagenes' , as: :delete_images
  delete 'registros/:id/delete' => 'registros#destroy'
  get 'perfils/:id/:nombre' => 'perfils#edit' , as: :editar_perfil
  get 'recomienda' => 'registros#recomienda' , as: :recomienda

  get 'registros/:id/:titulo' => 'registros#show' , as: :show
  
   get 'grupos' => 'grupos#index', as: :group
   post "/grupos/:id" => "grupos#show"

   root 'controlador#index'

    namespace :api do
    namespace :v1 do

      resources :directorios, path: "directorios"
      resources :get_direct, path: "get_direct"
      resources :get_imagen, path: "get_imagen"
      resources :get_comentarios, path: "get_comentarios"
      resources :get_respuestas, path: "get_respuestas"
      resources :get_megusta, path: "get_megusta"
      resources :servicios, path: "servicios"
      resources :servicio_all, path: "servicio_all"
      resources :directorios_random, path: "directorios_random"
      resources :bot_servicios, path: "bot_servicios"
    end
  end

end

app/models/unir.rb
class Unir < ActiveRecord::Base
end

app/controllers/unirs_controller.rb
class UnirsController < ApplicationController
  before_action :set_unir, only: [:show, :edit, :update, :destroy]

  # GET /unirs
  # GET /unirs.json
  def index
    @unirs = Unir.all
  end

  # GET /unirs/1
  # GET /unirs/1.json
  def show
  end

  # GET /unirs/new
  def new
    @unir = Unir.new
  end

  # GET /unirs/1/edit
  def edit
  end

  # POST /unirs
  # POST /unirs.json
  def create
    @unir = Unir.new(unir_params)

    respond_to do |format|
      if @unir.save
        format.html { redirect_to '/', notice: 'Unir was successfully created.' }
        format.json { render :show, status: :created, location: @unir }
      else
        format.html { render :new }
        format.json { render json: @unir.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /unirs/1
  # PATCH/PUT /unirs/1.json
  def update
    respond_to do |format|
      if @unir.update(unir_params)
        format.html { redirect_to @unir, notice: 'Unir was successfully updated.' }
        format.json { render :show, status: :ok, location: @unir }
      else
        format.html { render :edit }
        format.json { render json: @unir.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /unirs/1
  # DELETE /unirs/1.json
  def destroy
    @unir= Unir.find_by(:grupo_id)
    @unir.destroy
    respond_to do |format|
      format.html { redirect_to unirs_url, notice: 'Unir was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_unir
      @unir = Unir.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def unir_params
      params.require(:unir).permit(:grupo_id, :user_id)
    end
end

app/helpers/unirs_helper.rb
module UnirsHelper
end

app/views/unirs/_form.html.erb
<%= form_for(@unir) do |f| %>
  <% if @unir.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@unir.errors.count, "error") %> prohibited this unir from being saved:</h2>

      <ul>
      <% @unir.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :grupo_id %><br>
    <%= f.text_field :grupo_id %>
  </div>
  <div class="field">
    <%= f.label :user_id %><br>
    <%= f.text_field :user_id %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/unirs/edit.html.erb
<h1>Editing Unir</h1>

<%= render 'form' %>

<%= link_to 'Show', @unir %> |
<%= link_to 'Back', unirs_path %>

app/views/unirs/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Unirs</h1>

<table>
  <thead>
    <tr>
      <th>Grupo</th>
      <th>User</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @unirs.each do |unir| %>
      <tr>
        <td><%= unir.grupo_id %></td>
        <td><%= unir.user_id %></td>
        <td><%= link_to 'Show', unir %></td>
        <td><%= link_to 'Edit', edit_unir_path(unir) %></td>
        <td><%= link_to 'Destroy', unir, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Unir', new_unir_path %>

app/views/unirs/new.html.erb
<h1>New Unir</h1>

<%= render 'form' %>

<%= link_to 'Back', unirs_path %>

app/views/unirs/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Grupo:</strong>
  <%= @unir.grupo_id %>
</p>

<p>
  <strong>User:</strong>
  <%= @unir.user_id %>
</p>

<%= link_to 'Edit', edit_unir_path(@unir) %> |
<%= link_to 'Back', unirs_path %>