config/routes.rb
Rails.application.routes.draw do
  resources :megusta
  resources :respuesta
  resources :comentarios
  resources :fotos
  resources :unirs
  get 'choise/index'

  resources :grupos
  get 'controlador/index'

  resources :cps
  resources :perfils
  devise_for :users, :controllers => { :omniauth_callbacks => "callbacks" }
  get 'home/index'

  resources :registros
  get 'join' => 'registros#join', as: :join
  get 'privado' => 'registros#private', as: :private
  get 'comenzar' => 'registros#comenzar', as: :comenzar
  get 'home' => 'home#index', as: :home
  get 'perfil' => 'perfils#new', as: :profile
  get 'webhook' => 'bot#webhook', as: :webhook
  get 'bot/webhook' => 'bot#webhook'
  post 'bot/webhook' => 'bot#receive_message'
  get 'unjoin' => 'registros#eliminar' , as: :unjoin
  get 'delete_images' => 'registros#eliminar_imagenes' , as: :delete_images
  delete 'registros/:id/delete' => 'registros#destroy'
  get 'perfils/:id/:nombre' => 'perfils#edit' , as: :editar_perfil
  get 'recomienda' => 'registros#recomienda' , as: :recomienda

  get 'registros/:id/:titulo' => 'registros#show' , as: :show
  
   get 'grupos' => 'grupos#index', as: :group
   post "/grupos/:id" => "grupos#show"

   root 'controlador#index'

    namespace :api do
    namespace :v1 do

      resources :directorios, path: "directorios"
      resources :get_direct, path: "get_direct"
      resources :get_imagen, path: "get_imagen"
      resources :get_comentarios, path: "get_comentarios"
      resources :get_respuestas, path: "get_respuestas"
      resources :get_megusta, path: "get_megusta"
      resources :servicios, path: "servicios"
      resources :servicio_all, path: "servicio_all"
      resources :directorios_random, path: "directorios_random"
      resources :bot_servicios, path: "bot_servicios"
    end
  end

end

app/models/comentario.rb
class Comentario < ActiveRecord::Base
end

app/models/cp.rb
class Cp < ActiveRecord::Base
end

app/models/foto.rb
class Foto < ActiveRecord::Base
	mount_uploader :photo, ImagenUploader
end

app/models/grupo.rb
class Grupo < ActiveRecord::Base
before_save :default_values
has_many :registros
	def default_values
      if self.id.nil?
        self.publicado = "Pendiente"
        self.tipo = "Publico"
      else
      end
  	end
  	def paypal_url(return_path)
  	valor = id + clave.to_i
    name = nombre
    values = {
      :business => 'negocio-1@vianse.mx',
      :upload => 1,
      :no_shipping => 1,
      :return => "#{Rails.application.secrets.app_host}#{return_path}",
      :notify_url => "#{Rails.application.secrets.app_host}/hook",
      :invoice => valor,
      :currency_code => 'USD',
      :item_name => name,
    }
    values.merge!({
         cmd:'_xclick-subscriptions',
         a3: 10,
         p3: 1,
         srt: 12,
         t3:  "Month",

      })


 
    # values.merge!({
    #                 cmd: "",
    #                 a3: price,
    #                 p3: 1,
    #                 srt: cycles,
    #                 t3: period.first
    #            })

              

    "https://www.sandbox.paypal.com/cgi-bin/webscr?" + values.to_query
  end
end

app/models/megustum.rb
class Megustum < ActiveRecord::Base
end

app/models/perfil.rb
class Perfil < ActiveRecord::Base
	mount_uploader :photo, ImagenUploader

	def to_param

		"#{id} #{nombre}".parameterize
	end
end

app/models/registro.rb
class Registro < ActiveRecord::Base
	before_save :default_values
	belongs_to :grupo
	self.per_page = 20
	mount_uploader :logo, ImagenUploader
	def to_param

		"#{id} #{titulo}".parameterize
	end


  def default_values
      if self.id.nil?
        self.countclicks = 0
      else
      end
  end
	
end

app/models/respuestum.rb
class Respuestum < ActiveRecord::Base
end

app/models/unir.rb
class Unir < ActiveRecord::Base
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  #devise :database_authenticatable, :registerable,
  #       :recoverable, :rememberable, :trackable, :validatable

  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable,
     :omniauthable, :omniauth_providers => [:facebook]

  def self.from_omniauth(auth)


      where(provider: auth.provider, uid: auth.uid).first_or_create do |user|
        user.provider = auth.provider
        user.uid = auth.uid
        user.name = auth.info.name
        user.photo = auth.info.image
        user.email = auth.info.email if auth.info.email
        user.password = Devise.friendly_token[0,20]


      end
  end




end

app/controllers/bot_controller.rb
class BotController < ApplicationController
 def webhook
   if params['hub.verify_token'] == "EAAWmSTe58XEBAKPYvuI8xqEiVxAPU7LuplSC6Q9qc4HW0T7cKSMAZC4XsmnEiGJpMv8ghqSHTqcLTzIUIhtKzPACUdUkkffEslu7aXqmiXfL760N3LR48fj507kWmFTBj1ZAi3QYeeJYknsuo7ZAA5Tvw3ZBFZCwJcfaLFDL0VQZDZD"
     render text: params['hub.challenge'] and return
   else
     render text: 'error' and return
   end
  end
end

app/controllers/comentarios_controller.rb
class ComentariosController < ApplicationController
  before_action :set_comentario, only: [:show, :edit, :update, :destroy]

  # GET /comentarios
  # GET /comentarios.json
  def index
    @comentarios = Comentario.all
  end

  # GET /comentarios/1
  # GET /comentarios/1.json
  def show
  end

  # GET /comentarios/new
  def new
    @comentario = Comentario.new
  end

  # GET /comentarios/1/edit
  def edit
  end

  # POST /comentarios
  # POST /comentarios.json
  def create
    @comentario = Comentario.new(comentario_params)

    respond_to do |format|
      if @comentario.save
        @user = Registro.where(:id => comentario_params[:registro_id]).pluck(:user_id).first
        @email= User.where(:id => @user).pluck(:email)
          RestClient.post "https://api:key-e7d79c66e74391fdf48b657624f23ddc"\
        "@api.mailgun.net/v3/sandboxb9c2dadab0ea49f6b7130d1091646c59.mailgun.org/messages",
        :from => "Bikina <no-reply@bikina.mx>",
        :to => @email,
        :subject => "Has recibido un comentario sobre tu producto",
        :html => "<p>El usuario #{current_user.email} te ha preguntado lo siguiente:</p>"\
                 "<p>#{comentario_params[:comentario]}.</p>"\
                 "<p>Entra a Bikina y responde su mensaje</p>"\
                 "<span>Atte. Bikina team</span>"
                 
        format.html { redirect_to :back, notice: 'Comentario was successfully created.' }
        format.json { render :show, status: :created, location: @comentario }
      else
        format.html { render :new }
        format.json { render json: @comentario.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /comentarios/1
  # PATCH/PUT /comentarios/1.json
  def update
    respond_to do |format|
      if @comentario.update(comentario_params)
        format.html { redirect_to @comentario, notice: 'Comentario was successfully updated.' }
        format.json { render :show, status: :ok, location: @comentario }
      else
        format.html { render :edit }
        format.json { render json: @comentario.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /comentarios/1
  # DELETE /comentarios/1.json
  def destroy
    @comentario.destroy
    respond_to do |format|
      format.html { redirect_to comentarios_url, notice: 'Comentario was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_comentario
      @comentario = Comentario.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def comentario_params
      params.require(:comentario).permit(:comentario, :user_id, :grupo_id, :registro_id,:name_user)
    end
end

app/helpers/choise_helper.rb
module ChoiseHelper
end

app/helpers/comentarios_helper.rb
module ComentariosHelper
end

app/helpers/cps_helper.rb
module CpsHelper
end

app/helpers/fotos_helper.rb
module FotosHelper
end

app/helpers/grupos_helper.rb
module GruposHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/megusta_helper.rb
module MegustaHelper
end

app/helpers/perfils_helper.rb
module PerfilsHelper
end

app/helpers/registros_helper.rb
module RegistrosHelper
end

app/helpers/respuesta_helper.rb
module RespuestaHelper
end

app/helpers/unirs_helper.rb
module UnirsHelper
end

app/views/comentarios/_form.html.erb
<%= form_for(@comentario) do |f| %>
  <% if @comentario.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@comentario.errors.count, "error") %> prohibited this comentario from being saved:</h2>

      <ul>
      <% @comentario.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :comentario %><br>
    <%= f.text_field :comentario %>
  </div>
  <div class="field">
    <%= f.label :user_id %><br>
    <%= f.text_field :user_id %>
  </div>
  <div class="field">
    <%= f.label :grupo_id %><br>
    <%= f.text_field :grupo_id %>
  </div>
  <div class="field">
    <%= f.label :registro_id %><br>
    <%= f.text_field :registro_id %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/comentarios/edit.html.erb
<h1>Editing Comentario</h1>

<%= render 'form' %>

<%= link_to 'Show', @comentario %> |
<%= link_to 'Back', comentarios_path %>

app/views/comentarios/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Comentarios</h1>

<table>
  <thead>
    <tr>
      <th>Comentario</th>
      <th>User</th>
      <th>Grupo</th>
      <th>Registro</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @comentarios.each do |comentario| %>
      <tr>
        <td><%= comentario.comentario %></td>
        <td><%= comentario.user_id %></td>
        <td><%= comentario.grupo_id %></td>
        <td><%= comentario.registro_id %></td>
        <td><%= link_to 'Show', comentario %></td>
        <td><%= link_to 'Edit', edit_comentario_path(comentario) %></td>
        <td><%= link_to 'Destroy', comentario, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Comentario', new_comentario_path %>

app/views/comentarios/new.html.erb
<h1>New Comentario</h1>

<%= render 'form' %>

<%= link_to 'Back', comentarios_path %>

app/views/comentarios/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Comentario:</strong>
  <%= @comentario.comentario %>
</p>

<p>
  <strong>User:</strong>
  <%= @comentario.user_id %>
</p>

<p>
  <strong>Grupo:</strong>
  <%= @comentario.grupo_id %>
</p>

<p>
  <strong>Registro:</strong>
  <%= @comentario.registro_id %>
</p>

<%= link_to 'Edit', edit_comentario_path(@comentario) %> |
<%= link_to 'Back', comentarios_path %>