config/routes.rb
Rails.application.routes.draw do
  resources :megusta
  resources :respuesta
  resources :comentarios
  resources :fotos
  resources :unirs
  get 'choise/index'

  resources :grupos
  get 'controlador/index'

  resources :cps
  resources :perfils
  devise_for :users, :controllers => { :omniauth_callbacks => "callbacks" }
  get 'home/index'

  resources :registros
  get 'join' => 'registros#join', as: :join
  get 'privado' => 'registros#private', as: :private
  get 'comenzar' => 'registros#comenzar', as: :comenzar
  get 'home' => 'home#index', as: :home
  get 'perfil' => 'perfils#new', as: :profile
  get 'webhook' => 'bot#webhook', as: :webhook
  get 'bot/webhook' => 'bot#webhook'
  post 'bot/webhook' => 'bot#receive_message'
  get 'unjoin' => 'registros#eliminar' , as: :unjoin
  get 'delete_images' => 'registros#eliminar_imagenes' , as: :delete_images
  delete 'registros/:id/delete' => 'registros#destroy'
  get 'perfils/:id/:nombre' => 'perfils#edit' , as: :editar_perfil
  get 'recomienda' => 'registros#recomienda' , as: :recomienda

  get 'registros/:id/:titulo' => 'registros#show' , as: :show
  
   get 'grupos' => 'grupos#index', as: :group
   post "/grupos/:id" => "grupos#show"

   root 'controlador#index'

    namespace :api do
    namespace :v1 do

      resources :directorios, path: "directorios"
      resources :get_direct, path: "get_direct"
      resources :get_imagen, path: "get_imagen"
      resources :get_comentarios, path: "get_comentarios"
      resources :get_respuestas, path: "get_respuestas"
      resources :get_megusta, path: "get_megusta"
      resources :servicios, path: "servicios"
      resources :servicio_all, path: "servicio_all"
      resources :directorios_random, path: "directorios_random"
      resources :bot_servicios, path: "bot_servicios"
    end
  end

end

app/models/grupo.rb
class Grupo < ActiveRecord::Base
before_save :default_values
has_many :registros
	def default_values
      if self.id.nil?
        self.publicado = "Pendiente"
        self.tipo = "Publico"
      else
      end
  	end
  	def paypal_url(return_path)
  	valor = id + clave.to_i
    name = nombre
    values = {
      :business => 'negocio-1@vianse.mx',
      :upload => 1,
      :no_shipping => 1,
      :return => "#{Rails.application.secrets.app_host}#{return_path}",
      :notify_url => "#{Rails.application.secrets.app_host}/hook",
      :invoice => valor,
      :currency_code => 'USD',
      :item_name => name,
    }
    values.merge!({
         cmd:'_xclick-subscriptions',
         a3: 10,
         p3: 1,
         srt: 12,
         t3:  "Month",

      })


 
    # values.merge!({
    #                 cmd: "",
    #                 a3: price,
    #                 p3: 1,
    #                 srt: cycles,
    #                 t3: period.first
    #            })

              

    "https://www.sandbox.paypal.com/cgi-bin/webscr?" + values.to_query
  end
end

app/controllers/grupos_controller.rb
class GruposController < ApplicationController
  before_action :set_grupo, only: [:show, :edit, :update, :destroy]

  # GET /grupos
  # GET /grupos.json
  def index
    @grupos = Grupo.all
  end

  # GET /grupos/1
  # GET /grupos/1.json
  def show
  end

  # GET /grupos/new
  def new
    @grupo = Grupo.new
  end

  # GET /grupos/1/edit
  def edit
  end

  # POST /grupos
  # POST /grupos.json
  def create
    @grupo = Grupo.new(grupo_params)
    logger.debug grupo_params[:nombre]
    respond_to do |format|
      if @grupo.save
  RestClient.post "https://api:key-e7d79c66e74391fdf48b657624f23ddc"\
  "@api.mailgun.net/v3/sandboxb9c2dadab0ea49f6b7130d1091646c59.mailgun.org/messages",
  :from => "Bikina <no-reply@bikina.mx>",
  :to => "krlos013@gmail.com",
  :subject => "Solicitud de creación de directorio",
  :html => "El usuario #{current_user.email} solicita la creación de un nuevo directorio, a continuación los detalles:"\
           "<p>Nombre: #{grupo_params[:nombre]}, clave: #{grupo_params[:clave]}</p>"\
           "<p>Descripción: #{grupo_params[:descripcion]} </p>"
        format.html { redirect_to '/', notice: 'Grupo was successfully created.' }
        format.json { render :show, status: :created, location: @grupo }
      else
        format.html { render :new }
        format.json { render json: @grupo.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /grupos/1
  # PATCH/PUT /grupos/1.json
  def update
    respond_to do |format|
      if @grupo.update(grupo_params)
        format.html { redirect_to @grupo, notice: 'Grupo was successfully updated.' }
        format.json { render :show, status: :ok, location: @grupo }
      else
        format.html { render :edit }
        format.json { render json: @grupo.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /grupos/1
  # DELETE /grupos/1.json
  def destroy
    @grupo.destroy
    respond_to do |format|
      format.html { redirect_to grupos_url, notice: 'Grupo was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_grupo
      @grupo = Grupo.find(params[:id])
    end



    # Never trust parameters from the scary internet, only allow the white list through.
    def grupo_params
      params.require(:grupo).permit(:nombre, :descripcion, :user_id, :clave, :tipo, :cp)
    end
end

app/helpers/grupos_helper.rb
module GruposHelper
end

app/views/grupos/_form.html.erb
<%= form_for(@grupo) do |f| %>
  <% if @grupo.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@grupo.errors.count, "error") %> prohibited this grupo from being saved:</h2>

      <ul>
      <% @grupo.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label "Nombre del directorio" %><br>
    <%= f.text_field :nombre %>
  </div>
  <div class="field">
    <%= f.hidden_field :user_id, :value => current_user.id %>
  </div>
  <div class="field">
    <%= f.hidden_field :clave, :value => rand(5..100000000) %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/grupos/edit.html.erb
<h1>Editing Grupo</h1>

<%= render 'form' %>

<%= link_to 'Show', @grupo %> |
<%= link_to 'Back', grupos_path %>

app/views/grupos/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Grupos</h1>

<table>
  <thead>
    <tr>
      <th>Nombre</th>
      <th>User</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @grupos.each do |grupo| %>
      <tr>
        <td><%= grupo.nombre %></td>
        <td><%= grupo.user_id %></td>
        <td><%= params[:txn_id] %> </td>
        <td><%= link_to 'Show', grupo %></td>
        <td><%= link_to 'Edit', edit_grupo_path(grupo) %></td>
        <td><%= link_to 'Destroy', grupo, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Grupo', new_grupo_path %>

app/views/grupos/new.html.erb
<h1>Nuevo Directorio</h1>

<%= render 'form' %>

<%= link_to 'Back', grupos_path %>

app/views/grupos/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Nombre:</strong>
  <%= @grupo.nombre %>
</p>

<p>
  <strong>User:</strong>
  <%= @grupo.user_id %>
</p>

<%= link_to 'Edit', edit_grupo_path(@grupo) %> |
<%= link_to 'Back', grupos_path %>