config/routes.rb
Rails.application.routes.draw do
  resources :megusta
  resources :respuesta
  resources :comentarios
  resources :fotos
  resources :unirs
  get 'choise/index'

  resources :grupos
  get 'controlador/index'

  resources :cps
  resources :perfils
  devise_for :users, :controllers => { :omniauth_callbacks => "callbacks" }
  get 'home/index'

  resources :registros
  get 'join' => 'registros#join', as: :join
  get 'privado' => 'registros#private', as: :private
  get 'comenzar' => 'registros#comenzar', as: :comenzar
  get 'home' => 'home#index', as: :home
  get 'perfil' => 'perfils#new', as: :profile
  get 'webhook' => 'bot#webhook', as: :webhook
  get 'bot/webhook' => 'bot#webhook'
  post 'bot/webhook' => 'bot#receive_message'
  get 'unjoin' => 'registros#eliminar' , as: :unjoin
  get 'delete_images' => 'registros#eliminar_imagenes' , as: :delete_images
  delete 'registros/:id/delete' => 'registros#destroy'
  get 'perfils/:id/:nombre' => 'perfils#edit' , as: :editar_perfil
  get 'recomienda' => 'registros#recomienda' , as: :recomienda

  get 'registros/:id/:titulo' => 'registros#show' , as: :show
  
   get 'grupos' => 'grupos#index', as: :group
   post "/grupos/:id" => "grupos#show"

   root 'controlador#index'

    namespace :api do
    namespace :v1 do

      resources :directorios, path: "directorios"
      resources :get_direct, path: "get_direct"
      resources :get_imagen, path: "get_imagen"
      resources :get_comentarios, path: "get_comentarios"
      resources :get_respuestas, path: "get_respuestas"
      resources :get_megusta, path: "get_megusta"
      resources :servicios, path: "servicios"
      resources :servicio_all, path: "servicio_all"
      resources :directorios_random, path: "directorios_random"
      resources :bot_servicios, path: "bot_servicios"
    end
  end

end

app/models/foto.rb
class Foto < ActiveRecord::Base
	mount_uploader :photo, ImagenUploader
end

app/controllers/fotos_controller.rb
class FotosController < ApplicationController
  before_action :set_foto, only: [:show, :edit, :update, :destroy]

  # GET /fotos
  # GET /fotos.json
  def index
    @fotos = Foto.all
  end

  # GET /fotos/1
  # GET /fotos/1.json
  def show
  end

  # GET /fotos/new
  def new
    @foto = Foto.new
  end

  # GET /fotos/1/edit
  def edit
  end

  # POST /fotos
  # POST /fotos.json
  def create
    @foto = Foto.new(foto_params)

    respond_to do |format|
      if @foto.save
        format.html { redirect_to :back, notice: 'Foto was successfully created.' }
        format.json { render :show, status: :created, location: @foto }
      else
        format.html { render :new }
        format.json { render json: @foto.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /fotos/1
  # PATCH/PUT /fotos/1.json
  def update
    respond_to do |format|
      if @foto.update(foto_params)
        format.html { redirect_to @foto}
        format.json { render :show, status: :ok, location: @foto }
      else
        format.html { render :edit }
        format.json { render json: @foto.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /fotos/1
  # DELETE /fotos/1.json
  def destroy
    @foto.destroy
    respond_to do |format|
      format.html { redirect_to :back, notice: 'Foto was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_foto
      @foto = Foto.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def foto_params
      params.require(:foto).permit(:photo, :registro_id,:user_id, :grupo_id)
    end
end

app/helpers/fotos_helper.rb
module FotosHelper
end

app/views/fotos/_form.html.erb
<%= form_for(@foto) do |f| %>
  <% if @foto.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@foto.errors.count, "error") %> prohibited this foto from being saved:</h2>

      <ul>
      <% @foto.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label I18n.t('form_foto_dg') %><br>
    <%= f.hidden_field :photo %>
    <%= f.file_field :photo,:class => 'form-control ' %>
    <%= f.hidden_field :remote_photo_url %>         
  </div>
  <div class="field">
    <%= f.label :user_id %><br>
    <%= f.text_field :user_id %>
  </div>
  <div class="field">
    <%= f.label :grupo_id %><br>
    <%= f.text_field :grupo_id %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/fotos/edit.html.erb
<h1>Editing Foto</h1>

<%= render 'form' %>

<%= link_to 'Show', @foto %> |
<%= link_to 'Back', fotos_path %>

app/views/fotos/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Fotos</h1>

<table>
  <thead>
    <tr>
      <th>Photo</th>
      <th>User</th>
      <th>Grupo</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @fotos.each do |foto| %>
      <tr>
        <td><%= foto.photo %></td>
        <td><%= foto.user_id %></td>
        <td><%= foto.grupo_id %></td>
        <td><%= link_to 'Show', foto %></td>
        <td><%= link_to 'Edit', edit_foto_path(foto) %></td>
        <td><%= link_to 'Destroy', foto, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Foto', new_foto_path %>

app/views/fotos/new.html.erb
<h1>New Foto</h1>

<%= render 'form' %>

<%= link_to 'Back', fotos_path %>

app/views/fotos/show.html.erb
<p>
  <strong>Photo:</strong>
  <%= @foto.photo %>
</p>

<p>
  <strong>User:</strong>
  <%= @foto.user_id %>
</p>

<p>
  <strong>Grupo:</strong>
  <%= @foto.grupo_id %>
</p>

<%= link_to 'Edit', edit_foto_path(@foto) %> |
<%= link_to 'Back', fotos_path %>